version: '3.8'

services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
    ports:
      - "81:80"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - ./database.txt:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: nadeen #Use environment variable

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql: