version: '3.8'

services:
  www:
    build:
      context: .  # Ensure this points to the directory containing the Dockerfile
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
    ports:
      - "81:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: nadeen
      MYSQL_DATABASE: dictionary
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8082:80"  # Changed from 8081 to 8082
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data:
